### ISSUE TITLE
All systemd timers not set to monthly run 1st of month at 0:00 in addition to PERIOD setting

### ISSUE THREAD

**Issue by CorrosiveTruths** [kdave/btrfsmaintenance#71] opened 2019-01-28 16:14 UTC
Affects all timers used in btrfsmaintenance.

Using btrfs-trim as an example:

I set the trim to run every Monday at 15:45 with the following setting.
/etc/default/btrfsmaintenance
BTRFS_TRIM_PERIOD="Monday 15:45"

Ran the refresh script with systemctl restart btrfsmaintenance-refresh

Ran fine at the allotted time, but then when I check the status of the timer.

systemctl status btrfs-trim.timer
Loaded: loaded (/lib/systemd/system/btrfs-trim.timer; enabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/btrfs-trim.timer.d
         └─schedule.conf
Trigger: Fri 2019-02-01 00:00:00 GMT; 3 days left

It will run next on the 1st (Friday) of the month at 0:00.

The timer is sourcing both OnCalendar=monthly from the timer section of /lib/systemd/system/btrfs-trim.timer and OnCalendar=Monday 15:45 from the timer section of /etc/systemd/system/btrfs-trim.timer.d/schedule.conf

Removing the OnCalendar=monthly from the timer section of /lib/systemd/system/btrfs-trim.timer and re-running the refresh script fixes the issue.

That won't persist after the package is updated though, so the workaround I'm using is to copy /lib/systemd/system/btrfs-trim.timer as /etc/systemd/system/btrfs-trim.timer and remove the OnCalendar=monthly from the timer section as systemd will read that file instead of the /lib version.

**Comment by CorrosiveTruths** [comment] 2019-01-28 16:16
Closed #65 for this.

**Comment by CorrosiveTruths** [comment] 2020-07-04 11:18
Probably easier to reset the OnCalendar in /etc/systemd/system/btrfs-trim.timer.d/schedule.conf.

E.g.:
OnCalendar=
OnCalendar=Monday 15:45

**Comment by AndreaPro** [comment] 2021-04-24 11:13
I've setup btrfsmaintenance on my Debian Buster system and I've noticed that the issue is still there

**Comment by Seb35** [comment] 2021-07-08 10:37
I also observe this. Given `OnCalendar=` can be specified multiple times (see [systemd.timer(5)](https://man7.org/linux/man-pages/man5/systemd.timer.5.html)), the files schedule.conf must indeed be:
```
[Timer]
OnCalendar=
OnCalendar=Monday 15:45
```

**Comment by kdave** [comment] 2021-07-21 09:38
Fixed by #94.

**Closed by kdave** 2021-07-21 09:38 UTC
Labels: bug
